// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3lXrVsL-bR2cKH68jsRSjlJ24_oQ2GBQ',
    appId: '1:469902866868:android:2c948ddbf1ed5e7b175ae1',
    messagingSenderId: '469902866868',
    projectId: 'veloo-firebase',
    storageBucket: 'veloo-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq4TIgkWEfHlKA355BT1t6RItJjpqGXfk',
    appId: '1:469902866868:ios:2e6cb837fd2f3ee6175ae1',
    messagingSenderId: '469902866868',
    projectId: 'veloo-firebase',
    storageBucket: 'veloo-firebase.firebasestorage.app',
    iosBundleId: 'com.example.veloo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq4TIgkWEfHlKA355BT1t6RItJjpqGXfk',
    appId: '1:469902866868:ios:2e6cb837fd2f3ee6175ae1',
    messagingSenderId: '469902866868',
    projectId: 'veloo-firebase',
    storageBucket: 'veloo-firebase.firebasestorage.app',
    iosBundleId: 'com.example.veloo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAsfyXJkyg84jWyhUBrndbVwqFobzUm1Y0",
    authDomain: "veloo-firebase.firebaseapp.com",
    projectId: "veloo-firebase",
    storageBucket: "veloo-firebase.firebasestorage.app",
    messagingSenderId: "469902866868",
    appId: "1:469902866868:web:e4574a01c2f8f303175ae1",
    measurementId: "G-3YGPLDZSGP"
  );

}