#!/usr/bin/env python3

__file__ = "multi.py"
__author__ = "David Kvaček (xkvace00@stud.fit.vutbr.cz)"
__spec__ = "Multimodal late-fusion system for person detection using audio and image subsystems."
__date__ = "2026-05-04"

import os


def load_subsystem_scores(file_path):
    """
    Reads the output text file generated by individual subsystems.

    Parses the tab/space-separated file containing filename, probability score,
    and hard decision for each sample.

    Args:
        file_path (str): Path to the subsystem output file (.txt).

    Returns:
        dict: Dictionary mapping filenames to their probability scores.
    """
    scores_dict = {}

    if not os.path.exists(file_path):
        print(f"File {file_path} not found!")
        return scores_dict

    with open(file_path, 'r') as input_file:
        for line in input_file:
            parts = line.strip().split()
            if len(parts) >= 2:
                file_name = parts[0]
                probability_score = float(parts[1])
                scores_dict[file_name] = probability_score

    return scores_dict


if __name__ == "__main__":
    print("Loading subsystem scores...")
    image_scores = load_subsystem_scores("image.txt")
    audio_scores = load_subsystem_scores("audio.txt")

    print(f"Image scores loaded: {len(image_scores)} samples")
    print(f"Audio scores loaded: {len(audio_scores)} samples")

    # find intersection of files present in both modalities
    common_files = set(image_scores.keys()).intersection(set(audio_scores.keys()))

    if not common_files:
        print("No common files found between image.txt and audio.txt!")
        exit(1)

    print(f"Fusing scores for {len(common_files)} common files...")

    # sort files alphabetically
    sorted_common_files = sorted(list(common_files))

    with open('multi.txt', 'w') as output_file:
        for file_name in sorted_common_files:
            image_probability = image_scores[file_name]
            audio_probability = audio_scores[file_name]

            # late fusion: arithmetic mean of probabilities from both modalities
            # assumes equal importance of both modalities
            fused_probability = (image_probability + audio_probability) / 2.0

            # hard decision based on 0.5 threshold (assuming equal prior probabilities)
            hard_decision = 1 if fused_probability >= 0.5 else 0

            output_file.write(f"{file_name} {fused_probability:.4f} {hard_decision}\n")

    print("Multimodal fusion complete")
    print("Fusion results saved to multi.txt")
