-- Implementace 3. ulohy do IDS 2022/23
-- Jmeno a prijmeni: David Kvacek
-- Login: xkvace00
-- Datum: 2023-04-09

-- DROP TABLES (odstraneni objektu z databaze)
DROP TABLE urednik CASCADE CONSTRAINTS;
DROP TABLE urad CASCADE CONSTRAINTS;
DROP TABLE skola CASCADE CONSTRAINTS;
DROP TABLE uzemni_pusobnost CASCADE CONSTRAINTS;
DROP TABLE rozhodnuti CASCADE CONSTRAINTS;
DROP TABLE funkce CASCADE CONSTRAINTS;
DROP TABLE zastava CASCADE CONSTRAINTS;
DROP TABLE studuje CASCADE CONSTRAINTS;

-- CREATE TABLES (vytvoreni objektu databaze)
CREATE TABLE urednik (
    osobni_cislo INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    jmeno VARCHAR(32) NOT NULL,
    prijmeni VARCHAR(32) NOT NULL,
    datum_narozeni DATE NOT NULL,
    pohlavi VARCHAR(16) NOT NULL,
    slechticky_titul VARCHAR(16)
);

CREATE TABLE uzemni_pusobnost (
    katastralni_cislo NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    kralovstvi VARCHAR(32),
    zeme VARCHAR(32),
    region VARCHAR(32),
    hrabstvi VARCHAR(32),
    okres VARCHAR(32),
    obec VARCHAR(32),

    -- kontrola formatu katastralniho cisla:
    -- 1) prvni cislice musi byt pouze 1 nebo 2 (druh cislovani)
    -- 2) nasleduje peticiferne kmenove cislo
    -- 3) dalsi tri cislice vyjadruji poddeleni
    -- 4) a posledni cislice znaci atribut parcely
    CHECK(REGEXP_LIKE(katastralni_cislo, '^[1-2][0-9]{9}$'))
);

-- vztah generalizace/specializace: urad i skola spadaji pod entitu instituce
-- (instituce nemodelovana - pouze tabulky pro podtypy i s atributy nadtypu),
-- tzn. obe entity dedi vsechny atributy, navic skola obsahuje atributy
-- obor, stupen a akademicky titul (v pripade uradu jsou tyto atributy irelevantni)
CREATE TABLE urad (
    zkratka NUMBER(3) GENERATED BY DEFAULT AS IDENTITY (START WITH 001 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    fk_urad_uzemni_pusobnost NUMBER(10) NOT NULL,
    nazev VARCHAR(64) NOT NULL,
    sidlo VARCHAR(32) NOT NULL,
    typ VARCHAR(32) NOT NULL,
    datum_zrizeni DATE NOT NULL,
    zrizovaci_dokument VARCHAR(64),
    datum_zaniku DATE,

    CONSTRAINT fk_urad_uzemni_pusobnost FOREIGN KEY(fk_urad_uzemni_pusobnost) REFERENCES uzemni_pusobnost(katastralni_cislo),

    -- kontrola dat, zda nasleduji chronologicky za sebou
    CHECK(datum_zrizeni <= datum_zaniku)
);

CREATE TABLE skola (
    zkratka NUMBER(3) GENERATED BY DEFAULT AS IDENTITY (START WITH 001 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    fk_skola_uzemni_pusobnost NUMBER(10) NOT NULL,
    nazev VARCHAR(64) NOT NULL,
    sidlo VARCHAR(32) NOT NULL,
    typ VARCHAR(32) NOT NULL,
    datum_zrizeni DATE NOT NULL,
    zrizovaci_dokument VARCHAR(64),
    datum_zaniku DATE,
    obor VARCHAR(64) NOT NULL,
    stupen NUMBER(2) NOT NULL,
    akademicky_titul VARCHAR(16),

    CONSTRAINT fk_skola_uzemni_pusobnost FOREIGN KEY(fk_skola_uzemni_pusobnost) REFERENCES uzemni_pusobnost(katastralni_cislo),

    -- kontrola dat, zda nasleduji chronologicky za sebou
    -- a zda je stupen vyssi cislo nez 0
    CHECK(datum_zrizeni <= datum_zaniku),
    CHECK(stupen > 0)
);

CREATE TABLE rozhodnuti (
    jednaci_cislo INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    fk_rozhodnuti_urednik INTEGER NOT NULL,
    fk_rozhodnuti_urad NUMBER(3),
    fk_rozhodnuti_skola NUMBER(3),
    datum_rozhodnuti DATE NOT NULL,
    datum_vykonatelnosti DATE NOT NULL,
    text_vlastniho_rozhodnuti VARCHAR(128) NOT NULL,
    text_oduvodneni VARCHAR(256) NOT NULL,

    CONSTRAINT fk_rozhodnuti_urednik FOREIGN KEY(fk_rozhodnuti_urednik) REFERENCES urednik(osobni_cislo),
    CONSTRAINT fk_rozhodnuti_urad FOREIGN KEY(fk_rozhodnuti_urad) REFERENCES urad(zkratka),
    CONSTRAINT fk_rozhodnuti_skola FOREIGN KEY(fk_rozhodnuti_skola) REFERENCES skola(zkratka),

    -- kontrola dat, zda nasleduji chronologicky za sebou
    -- a jestli rozhodnuti spada pod urad nebo skolu
    CHECK(datum_rozhodnuti <= datum_vykonatelnosti),
    CHECK(fk_rozhodnuti_urad IS NOT NULL OR fk_rozhodnuti_skola IS NOT NULL)
);

CREATE TABLE funkce (
    kod INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    fk_urad INTEGER,
    fk_skola INTEGER,
    nazev VARCHAR(32) NOT NULL,
    zpusob_ziskani VARCHAR(32) NOT NULL,
    delka_funkcniho_obdobi INTEGER NOT NULL,
    datum_zavedeni DATE NOT NULL,
    datum_zruseni DATE,

    CONSTRAINT fk_urad FOREIGN KEY(fk_urad) REFERENCES urad(zkratka),
    CONSTRAINT fk_skola FOREIGN KEY(fk_skola) REFERENCES skola(zkratka),

    -- kontrola, jestli je delka funkcniho obdobi validni cislo,
    -- zda data nasleduji chronologicky za sebou
    -- a jestli funkce spada pod urad nebo skolu
    CHECK(delka_funkcniho_obdobi > 0),
    CHECK(datum_zavedeni <= datum_zruseni),
    CHECK(fk_urad IS NOT NULL OR fk_skola IS NOT NULL)
);

CREATE TABLE zastava (
    fk_zastava_osobni_cislo INTEGER NOT NULL,
    fk_zastava_kod INTEGER NOT NULL,
    datum_zacatku DATE NOT NULL,
    datum_konce DATE,
    duvod_opusteni VARCHAR(32),
    poradi_obsazeni INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    CONSTRAINT fk_zastava_osobni_cislo FOREIGN KEY(fk_zastava_osobni_cislo) REFERENCES urednik(osobni_cislo),
    CONSTRAINT fk_zastava_kod FOREIGN KEY(fk_zastava_kod) REFERENCES funkce(kod),

    -- kontrola dat, zda nasleduji chronologicky za sebou
    -- a jestli je poradi obsazeni validni cislo
    CHECK(datum_zacatku <= datum_konce),
    CHECK(poradi_obsazeni > 0)
);

CREATE TABLE studuje (
    fk_studuje_osobni_cislo INTEGER NOT NULL,
    fk_studuje_zkratka NUMBER(3) NOT NULL,
    datum_zacatku DATE NOT NULL,
    datum_konce DATE,
    uspesne_zakonceni VARCHAR(16),

    CONSTRAINT fk_studuje_osobni_cislo FOREIGN KEY(fk_studuje_osobni_cislo) REFERENCES urednik(osobni_cislo),
    CONSTRAINT fk_studuje_zkratka FOREIGN KEY(fk_studuje_zkratka) REFERENCES skola(zkratka),

    -- kontrola dat, zda nasleduji chronologicky za sebou
    CHECK(datum_zacatku <= datum_konce)
);

-- INSERT INTO (vlozeni novych dat do databaze)
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Václav', 'Novák', TO_DATE('15.02.1985', 'dd.mm.yyyy'), 'muž', NULL);
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Petra', 'Horáková', TO_DATE('26.03.1972', 'dd.mm.yyyy'), 'žena', NULL);
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Jakub', 'Vávra', TO_DATE('12.07.1991', 'dd.mm.yyyy'), 'muž', NULL);
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Eliška', 'Kinská', TO_DATE('01.04.1960', 'dd.mm.yyyy'), 'žena', 'hraběnka');
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Martin', 'Schwarzenberg', TO_DATE('17.12.1978', 'dd.mm.yyyy'), 'muž', 'princ');
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Filip', 'Hanzl', TO_DATE('05.10.1997', 'dd.mm.yyyy'), 'muž', NULL);
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Alžběta', 'Dvořáková', TO_DATE('31.08.1950', 'dd.mm.yyyy'), 'žena', NULL);

INSERT INTO uzemni_pusobnost(kralovstvi, zeme, region, hrabstvi, okres, obec)
VALUES(NULL, 'Česká republika', 'Čechy', NULL, 'Praha', 'Praha');
INSERT INTO uzemni_pusobnost(kralovstvi, zeme, region, hrabstvi, okres, obec)
VALUES(NULL, 'Česká republika', 'Morava', NULL, 'Brno-město', 'Brno');

INSERT INTO urad(nazev, fk_urad_uzemni_pusobnost, sidlo, typ, datum_zrizeni, zrizovaci_dokument, datum_zaniku)
VALUES('Česká národní banka', 1000000000, 'Praha', 'centrální', TO_DATE('01.01.1993', 'dd.mm.yyyy'), 'Zákon č. 6/1993 Sb.', NULL);
INSERT INTO urad(nazev, fk_urad_uzemni_pusobnost, sidlo, typ, datum_zrizeni, zrizovaci_dokument, datum_zaniku)
VALUES('Český telekomunikační úřad', 1000000000, 'Praha', 'regulační', TO_DATE('01.05.2005', 'dd.mm.yyyy'), 'Zákon č. 127/2005 Sb.', NULL);
INSERT INTO urad(nazev, fk_urad_uzemni_pusobnost, sidlo, typ, datum_zrizeni, zrizovaci_dokument, datum_zaniku)
VALUES('Národní úřad pro kybernetickou a informační bezpečnost', 1000000001, 'Brno', 'správní', TO_DATE('01.08.2017', 'dd.mm.yyyy'), 'Zákon č. 205/2017 Sb.', NULL);
INSERT INTO urad(nazev, fk_urad_uzemni_pusobnost, sidlo, typ, datum_zrizeni, zrizovaci_dokument, datum_zaniku)
VALUES('Úřad pro ochranu hospodářské soutěže', 1000000001, 'Brno', 'správní', TO_DATE('01.11.1996', 'dd.mm.yyyy'), 'Zákon č. 273/1996 Sb.', NULL);

INSERT INTO skola(nazev, fk_skola_uzemni_pusobnost, sidlo, typ, datum_zrizeni, zrizovaci_dokument, datum_zaniku, obor, stupen, akademicky_titul)
VALUES('Vysoké učení technické v Brně', 1000000001, 'Brno', 'vzdělávací', TO_DATE('19.09.1899', 'dd.mm.yyyy'), NULL, NULL, 'Informační technologie', 1, 'Bc.');
INSERT INTO skola(nazev, fk_skola_uzemni_pusobnost, sidlo, typ, datum_zrizeni, zrizovaci_dokument, datum_zaniku, obor, stupen, akademicky_titul)
VALUES('Univerzita obrany', 1000000001, 'Brno', 'vzdělávací', TO_DATE('01.09.2004', 'dd.mm.yyyy'), NULL, NULL, 'Technologie pro obranu a bezpečnost – strojní', 1, 'Bc.');
INSERT INTO skola(nazev, fk_skola_uzemni_pusobnost, sidlo, typ, datum_zrizeni, zrizovaci_dokument, datum_zaniku, obor, stupen, akademicky_titul)
VALUES('Česká zemědělská univerzita v Praze', 1000000000, 'Praha', 'vzdělávací', TO_DATE('1952', 'yyyy'), NULL, NULL, 'Aplikovaná ekologie', 2, 'Mgr.');

INSERT INTO rozhodnuti(fk_rozhodnuti_urednik, fk_rozhodnuti_urad, fk_rozhodnuti_skola, datum_rozhodnuti, datum_vykonatelnosti, text_vlastniho_rozhodnuti, text_oduvodneni)
VALUES(4, NULL, 001, TO_DATE('01.01.2015', 'dd.mm.yyyy'), TO_DATE('01.09.2015', 'dd.mm.yyyy'), 'Rozhodnutí o uzavření fakulty.', 'Na základě dlouhodobého propadu zájmu studentů o uvedený obor bylo rozhodnuto o uzavření dané fakulty z provozních a ekonomických důvodů.');
INSERT INTO rozhodnuti(fk_rozhodnuti_urednik, fk_rozhodnuti_urad, fk_rozhodnuti_skola, datum_rozhodnuti, datum_vykonatelnosti, text_vlastniho_rozhodnuti, text_oduvodneni)
VALUES(5, 001, NULL, TO_DATE('05.11.2017', 'dd.mm.yyyy'), TO_DATE('01.12.2017', 'dd.mm.yyyy'), 'Rozhodnutí o výši úrokových sazeb u hypotečních úvěrů.', 'Vzhledem k aktuální situaci na trhu s nemovitostmi a úvěry byly stanoveny nové úrokové sazby u hypotečních úvěrů.');
INSERT INTO rozhodnuti(fk_rozhodnuti_urednik, fk_rozhodnuti_urad, fk_rozhodnuti_skola, datum_rozhodnuti, datum_vykonatelnosti, text_vlastniho_rozhodnuti, text_oduvodneni)
VALUES(1, 002, NULL, TO_DATE('15.06.2020', 'dd.mm.yyyy'), TO_DATE('01.07.2020', 'dd.mm.yyyy'), 'Rozhodnutí o sankcích vůči poskytovateli telefonních služeb.', 'Poskytovatel telefonních služeb porušil stanovené regulace tím, že neumožňoval zákazníkům přenášet svá telefonní čísla.');
INSERT INTO rozhodnuti(fk_rozhodnuti_urednik, fk_rozhodnuti_urad, fk_rozhodnuti_skola, datum_rozhodnuti, datum_vykonatelnosti, text_vlastniho_rozhodnuti, text_oduvodneni)
VALUES(2, 002, NULL, TO_DATE('01.02.2021', 'dd.mm.yyyy'), TO_DATE('15.02.2021', 'dd.mm.yyyy'), 'Rozhodnutí o prodloužení doby účinnosti zřizovacího dokumentu určitého úřadu.', 'Za účelem zachování kontinuity činnosti určitého úřadu bude doba účinnosti jeho zřizovacího dokumentu prodloužena o dalších 5 let.');
INSERT INTO rozhodnuti(fk_rozhodnuti_urednik, fk_rozhodnuti_urad, fk_rozhodnuti_skola, datum_rozhodnuti, datum_vykonatelnosti, text_vlastniho_rozhodnuti, text_oduvodneni)
VALUES(4, NULL, 003, TO_DATE('01.09.2022', 'dd.mm.yyyy'), TO_DATE('01.10.2022', 'dd.mm.yyyy'), 'Rozhodnutí o odvolání garanta určitého kurzu.', 'Na základě zjištění porušení interních předpisů a narušení dobrého jména školy bylo rozhodnuto o odvolání garanta určitého kurzu.');
INSERT INTO rozhodnuti(fk_rozhodnuti_urednik, fk_rozhodnuti_urad, fk_rozhodnuti_skola, datum_rozhodnuti, datum_vykonatelnosti, text_vlastniho_rozhodnuti, text_oduvodneni)
VALUES(3, 001, NULL, TO_DATE('22.09.2022', 'dd.mm.yyyy'), TO_DATE('01.10.2022', 'dd.mm.yyyy'), 'Rozhodnutí o přidělení bankovní licence novému subjektu.', 'Nový subjekt splnil stanovené podmínky pro získání bankovní licence a bude povolen k provozování bankovních služeb.');
INSERT INTO rozhodnuti(fk_rozhodnuti_urednik, fk_rozhodnuti_urad, fk_rozhodnuti_skola, datum_rozhodnuti, datum_vykonatelnosti, text_vlastniho_rozhodnuti, text_oduvodneni)
VALUES(4, NULL, 001, TO_DATE('01.01.2023', 'dd.mm.yyyy'), TO_DATE('01.02.2023', 'dd.mm.yyyy'), 'Rozhodnutí o schválení nového studijního oboru.', 'Na základě připraveného návrhu vedení školy a hodnocení akademických kapacit bylo schváleno zavedení nového studijního oboru.');

INSERT INTO funkce(fk_urad, nazev, zpusob_ziskani, delka_funkcniho_obdobi, datum_zavedeni, datum_zruseni)
VALUES(001, 'výkonný ředitel', 'výběrové řízení', 2190, TO_DATE('01.01.1993', 'dd.mm.yyyy'), NULL);
INSERT INTO funkce(fk_skola, nazev, zpusob_ziskani, delka_funkcniho_obdobi, datum_zavedeni, datum_zruseni)
VALUES(001, 'IT specialista', 'výběrové řízení', 1825, TO_DATE('15.02.2018', 'dd.mm.yyyy'), NULL);
INSERT INTO funkce(fk_skola, nazev, zpusob_ziskani, delka_funkcniho_obdobi, datum_zavedeni, datum_zruseni)
VALUES(001, 'provozní technik', 'jmenování', 1460, TO_DATE('01.01.2019', 'dd.mm.yyyy'), NULL);
INSERT INTO funkce(fk_skola, nazev, zpusob_ziskani, delka_funkcniho_obdobi, datum_zavedeni, datum_zruseni)
VALUES(001, 'personální asistent', 'jmenování', 730, TO_DATE('01.04.2020', 'dd.mm.yyyy'), TO_DATE('31.03.2022', 'dd.mm.yyyy'));
INSERT INTO funkce(fk_urad, nazev, zpusob_ziskani, delka_funkcniho_obdobi, datum_zavedeni, datum_zruseni)
VALUES(002, 'vedoucí marketingu', 'výběrové řízení', 1095, TO_DATE('01.05.2021', 'dd.mm.yyyy'), NULL);
INSERT INTO funkce(fk_urad, nazev, zpusob_ziskani, delka_funkcniho_obdobi, datum_zavedeni, datum_zruseni)
VALUES(002, 'vedoucí účetní', 'jmenování', 365, TO_DATE('01.07.2022', 'dd.mm.yyyy'), TO_DATE('30.06.2023', 'dd.mm.yyyy'));

INSERT INTO zastava(fk_zastava_osobni_cislo, fk_zastava_kod, datum_zacatku, datum_konce, duvod_opusteni)
VALUES(1, 3, TO_DATE('01.07.2019', 'dd.mm.yyyy'), NULL, NULL);
INSERT INTO zastava(fk_zastava_osobni_cislo, fk_zastava_kod, datum_zacatku, datum_konce, duvod_opusteni)
VALUES(1, 1, TO_DATE('01.01.2020', 'dd.mm.yyyy'), TO_DATE('01.01.2026', 'dd.mm.yyyy'), NULL);
INSERT INTO zastava(fk_zastava_osobni_cislo, fk_zastava_kod, datum_zacatku, datum_konce, duvod_opusteni)
VALUES(4, 6, TO_DATE('01.05.2021', 'dd.mm.yyyy'), NULL, NULL);
INSERT INTO zastava(fk_zastava_osobni_cislo, fk_zastava_kod, datum_zacatku, datum_konce, duvod_opusteni)
VALUES(2, 2, TO_DATE('01.01.2023', 'dd.mm.yyyy'), TO_DATE('01.01.2024', 'dd.mm.yyyy'), NULL);
INSERT INTO zastava(fk_zastava_osobni_cislo, fk_zastava_kod, datum_zacatku, datum_konce, duvod_opusteni)
VALUES(5, 1, TO_DATE('01.01.2023', 'dd.mm.yyyy'), NULL, NULL);
INSERT INTO zastava(fk_zastava_osobni_cislo, fk_zastava_kod, datum_zacatku, datum_konce, duvod_opusteni)
VALUES(5, 2, TO_DATE('01.01.2023', 'dd.mm.yyyy'), NULL, NULL);
INSERT INTO zastava(fk_zastava_osobni_cislo, fk_zastava_kod, datum_zacatku, datum_konce, duvod_opusteni)
VALUES(5, 6, TO_DATE('01.01.2023', 'dd.mm.yyyy'), NULL, NULL);

INSERT INTO studuje(fk_studuje_osobni_cislo, fk_studuje_zkratka, datum_zacatku, datum_konce, uspesne_zakonceni)
VALUES(1, 002, TO_DATE('20.09.2017', 'dd.mm.yyyy'), TO_DATE('15.07.2020', 'dd.mm.yyyy'), 'úspěšné');
INSERT INTO studuje(fk_studuje_osobni_cislo, fk_studuje_zkratka, datum_zacatku, datum_konce, uspesne_zakonceni)
VALUES(1, 003, TO_DATE('20.09.2020', 'dd.mm.yyyy'), NULL, NULL);
INSERT INTO studuje(fk_studuje_osobni_cislo, fk_studuje_zkratka, datum_zacatku, datum_konce, uspesne_zakonceni)
VALUES(2, 001, TO_DATE('20.09.2020', 'dd.mm.yyyy'), NULL, NULL);
INSERT INTO studuje(fk_studuje_osobni_cislo, fk_studuje_zkratka, datum_zacatku, datum_konce, uspesne_zakonceni)
VALUES(3, 001, TO_DATE('20.09.2022', 'dd.mm.yyyy'), NULL, NULL);

-- SELECT (vyber podmnoziny dat z databaze a jejich razeni)
-- dotaz, ktery vybere vsechny funkce zavedene na danem urade (Cesky telekomunikacni urad) serazene podle delky funkcniho obdobi [spojeni dvou tabulek]
SELECT DISTINCT funkce.nazev AS funkce, urad.nazev AS urad, funkce.delka_funkcniho_obdobi FROM funkce JOIN urad ON funkce.fk_urad = urad.zkratka WHERE urad.nazev = 'Český telekomunikační úřad' ORDER BY funkce.delka_funkcniho_obdobi DESC;

-- dotaz, ktery vybere vsechny urady se sidlem v dane obci (Brno) serazene podle data zrizeni [spojeni dvou tabulek]
SELECT DISTINCT urad.nazev AS urad, uzemni_pusobnost.obec AS sidlo, urad.datum_zrizeni FROM uzemni_pusobnost JOIN urad ON uzemni_pusobnost.katastralni_cislo = urad.fk_urad_uzemni_pusobnost WHERE uzemni_pusobnost.obec = 'Brno' ORDER BY urad.datum_zrizeni;

-- dotaz, ktery vybere vsechny uredniky, kteri provedli rozhodnuti spadajici pod urcitou skolu (Vysoke uceni technicke v Brne) serazene podle prijmeni [spojeni tri tabulek]
SELECT DISTINCT urednik.jmeno, urednik.prijmeni, skola.nazev AS skola FROM urednik JOIN rozhodnuti ON urednik.osobni_cislo = rozhodnuti.fk_rozhodnuti_urednik JOIN skola ON rozhodnuti.fk_rozhodnuti_skola = skola.zkratka WHERE skola.nazev = 'Vysoké učení technické v Brně' ORDER BY urednik.prijmeni;

-- dotaz, ktery vybere vsechny uredniky, kteri zastavaji nejakou funkci serazene podle poctu zastavanych funkci [klauzule GROUP BY s agregacni funkci COUNT]
SELECT DISTINCT urednik.jmeno, urednik.prijmeni, COUNT(urednik.osobni_cislo) AS pocet_funkci FROM urednik JOIN zastava ON urednik.osobni_cislo = zastava.fk_zastava_osobni_cislo GROUP BY urednik.jmeno, urednik.prijmeni ORDER BY pocet_funkci DESC;

-- dotaz, ktery vybere vsechny urady, pod ktere spadaji rozhodnuti ucinena pred urcitym datem (01.01.2022) serazene podle poctu rozhodnuti [klauzule GROUP BY s agregacni funkci COUNT]
SELECT DISTINCT urad.nazev AS urad, COUNT(rozhodnuti.fk_rozhodnuti_urad) AS pocet_rozhodnuti FROM urad JOIN rozhodnuti ON urad.zkratka = rozhodnuti.fk_rozhodnuti_urad WHERE rozhodnuti.datum_rozhodnuti < TO_DATE('01.01.2022', 'dd.mm.yyyy') GROUP BY urad.nazev ORDER BY pocet_rozhodnuti DESC;

-- dotaz, ktery vybere vsechny uredniky, kteri dosud neudelali zadne rozhodnuti serazene podle prijmeni [predikat EXISTS]
SELECT DISTINCT urednik.jmeno, urednik.prijmeni FROM urednik WHERE NOT EXISTS(SELECT * FROM rozhodnuti WHERE rozhodnuti.fk_rozhodnuti_urednik = urednik.osobni_cislo) ORDER BY urednik.prijmeni;

-- dotaz, ktery vybere vsechna rozhodnuti spadajici pod urcitou skolu (Vysoke uceni technicke v Brne) serazena podle data rozhodnuti [predikat IN]
SELECT DISTINCT skola.nazev AS skola, rozhodnuti.text_vlastniho_rozhodnuti, rozhodnuti.datum_rozhodnuti FROM rozhodnuti JOIN skola ON rozhodnuti.fk_rozhodnuti_skola = skola.zkratka WHERE rozhodnuti.fk_rozhodnuti_skola IN(SELECT skola.zkratka FROM skola WHERE skola.nazev = 'Vysoké učení technické v Brně') ORDER BY rozhodnuti.datum_rozhodnuti;

COMMIT;
