-- Implementace 2. ulohy do IDS 2022/23
-- Jmeno a prijmeni: David Kvacek
-- Login: xkvace00
-- Datum: 2023-03-26

-- DROP TABLES (odstraneni objektu z databaze)
DROP TABLE urednik CASCADE CONSTRAINTS;
DROP TABLE urad CASCADE CONSTRAINTS;
DROP TABLE skola CASCADE CONSTRAINTS;
DROP TABLE uzemni_pusobnost CASCADE CONSTRAINTS;
DROP TABLE rozhodnuti CASCADE CONSTRAINTS;
DROP TABLE funkce CASCADE CONSTRAINTS;
DROP TABLE zastava CASCADE CONSTRAINTS;
DROP TABLE studuje CASCADE CONSTRAINTS;

-- CREATE TABLES (vytvoreni objektu databaze)
CREATE TABLE urednik (
    osobni_cislo INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    jmeno VARCHAR(32) NOT NULL,
    prijmeni VARCHAR(32) NOT NULL,
    datum_narozeni DATE NOT NULL,
    pohlavi VARCHAR(16) NOT NULL,
    slechticky_titul VARCHAR(16)
);

-- vztah generalizace/specializace: urad i skola spadaji pod entitu instituce
-- (instituce nemodelovana - pouze tabulky pro podtypy i s atributy nadtypu),
-- tzn. obe entity dedi vsechny atributy, navic skola obsahuje atributy
-- obor, stupen a akademicky titul (v pripade uradu jsou tyto atributy irelevantni)
CREATE TABLE urad (
    zkratka NUMBER(3) GENERATED BY DEFAULT AS IDENTITY (START WITH 001 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    nazev VARCHAR(64) NOT NULL,
    sidlo VARCHAR(32) NOT NULL,
    typ VARCHAR(32) NOT NULL,
    datum_zrizeni DATE NOT NULL,
    zrizovaci_dokument VARCHAR(64),
    datum_zaniku DATE,

    -- kontrola dat, zda nasleduji chronologicky za sebou
    CHECK(datum_zrizeni <= datum_zaniku)
);

CREATE TABLE skola (
    zkratka NUMBER(3) GENERATED BY DEFAULT AS IDENTITY (START WITH 001 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    nazev VARCHAR(64) NOT NULL,
    sidlo VARCHAR(32) NOT NULL,
    typ VARCHAR(32) NOT NULL,
    datum_zrizeni DATE NOT NULL,
    zrizovaci_dokument VARCHAR(64),
    datum_zaniku DATE,
    obor VARCHAR(32) NOT NULL,
    stupen NUMBER(2) NOT NULL,
    akademicky_titul VARCHAR(16),

    -- kontrola dat, zda nasleduji chronologicky za sebou
    -- a zda je stupen vyssi cislo nez 0
    CHECK(datum_zrizeni <= datum_zaniku),
    CHECK(stupen > 0)
);

CREATE TABLE uzemni_pusobnost (
    katastralni_cislo NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    kralovstvi VARCHAR(32),
    zeme VARCHAR(32),
    region VARCHAR(32),
    hrabstvi VARCHAR(32),
    okres VARCHAR(32),
    obec VARCHAR(32),

    -- kontrola formatu katastralniho cisla:
    -- 1) prvni cislice musi byt pouze 1 nebo 2 (druh cislovani)
    -- 2) nasleduje peticiferne kmenove cislo
    -- 3) dalsi tri cislice vyjadruji poddeleni
    -- 4) a posledni cislice znaci atribut parcely
    CHECK(REGEXP_LIKE(katastralni_cislo, '^[1-2][0-9]{9}$'))
);

CREATE TABLE rozhodnuti (
    jednaci_cislo INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    datum_rozhodnuti DATE NOT NULL,
    datum_vykonatelnosti DATE NOT NULL,
    text_vlastniho_rozhodnuti VARCHAR(128) NOT NULL,
    text_oduvodneni VARCHAR(256) NOT NULL,

    -- kontrola dat, zda nasleduji chronologicky za sebou
    CHECK(datum_rozhodnuti <= datum_vykonatelnosti)
);

CREATE TABLE funkce (
    kod INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    fk_funkce INTEGER NOT NULL,
    nazev VARCHAR(32) NOT NULL,
    zpusob_ziskani VARCHAR(32) NOT NULL,
    delka_funkcniho_obdobi INTEGER NOT NULL,
    datum_zavedeni DATE NOT NULL,
    datum_zruseni DATE,

    CONSTRAINT fk_funkce FOREIGN KEY(fk_funkce) REFERENCES urad(zkratka),

    -- kontrola, jestli je delka funkcniho obdobi validni cislo
    -- a zda data nasleduji chronologicky za sebou
    CHECK(delka_funkcniho_obdobi > 0),
    CHECK(datum_zavedeni <= datum_zruseni)
);

CREATE TABLE zastava (
    fk_zastava_osobni_cislo INTEGER NOT NULL,
    fk_kod INTEGER NOT NULL,
    datum_zacatku DATE NOT NULL,
    datum_konce DATE,
    duvod_opusteni VARCHAR(32),
    poradi_obsazeni INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,

    CONSTRAINT fk_zastava_osobni_cislo FOREIGN KEY(fk_zastava_osobni_cislo) REFERENCES urednik(osobni_cislo),
    CONSTRAINT fk_kod FOREIGN KEY(fk_kod) REFERENCES urad(zkratka),

    -- kontrola dat, zda nasleduji chronologicky za sebou
    -- a jestli je poradi obsazeni validni cislo
    CHECK(datum_zacatku <= datum_konce),
    CHECK(poradi_obsazeni > 0)
);

CREATE TABLE studuje (
    fk_studuje_osobni_cislo INTEGER NOT NULL,
    fk_zkratka NUMBER(3) NOT NULL,
    datum_zacatku DATE NOT NULL,
    datum_konce DATE,
    uspesne_zakonceni VARCHAR(16),

    CONSTRAINT fk_studuje_osobni_cislo FOREIGN KEY(fk_studuje_osobni_cislo) REFERENCES urednik(osobni_cislo),
    CONSTRAINT fk_zkratka FOREIGN KEY(fk_zkratka) REFERENCES skola(zkratka),

    -- kontrola dat, zda nasleduji chronologicky za sebou
    CHECK(datum_zacatku <= datum_konce)
);

-- ALTER TABLE (zmeny existujicich objektu databaze)
-- stanoveni kompozitniho klice sestavajiciho z diskriminatoru a ciziho klice
ALTER TABLE funkce ADD CONSTRAINT d_funkce PRIMARY KEY(kod, fk_funkce);

-- INSERT INTO (vlozeni novych dat do databaze)
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Jan', 'Novák', TO_DATE('15.02.1985', 'dd.mm.yyyy'), 'muž', NULL);
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Petra', 'Horáková', TO_DATE('26.03.1972', 'dd.mm.yyyy'), 'žena', NULL);
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Jakub', 'Vávra', TO_DATE('12.07.1991', 'dd.mm.yyyy'), 'muž', NULL);
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Jana', 'Kinská', TO_DATE('01.04.1960', 'dd.mm.yyyy'), 'žena', 'hraběnka');
INSERT INTO urednik(jmeno, prijmeni, datum_narozeni, pohlavi, slechticky_titul)
VALUES('Martin', 'Schwarzenberg', TO_DATE('17.12.1978', 'dd.mm.yyyy'), 'muž', 'princ');

INSERT INTO urad(nazev, sidlo, typ, datum_zrizeni, zrizovaci_dokument, datum_zaniku)
VALUES('Česká národní banka', 'Praha', 'centrální', TO_DATE('01.01.1993', 'dd.mm.yyyy'), 'Zákon č. 6/1993 Sb.', NULL);
INSERT INTO urad(nazev, sidlo, typ, datum_zrizeni, zrizovaci_dokument, datum_zaniku)
VALUES('Český telekomunikační úřad', 'Praha', 'regulační', TO_DATE('01.05.2005', 'dd.mm.yyyy'), 'Zákon č. 127/2005 Sb.', NULL);

INSERT INTO skola(nazev, sidlo, typ, datum_zrizeni, zrizovaci_dokument, datum_zaniku, obor, stupen, akademicky_titul)
VALUES('Vysoké učení technické v Brně', 'Brno', 'vzdělávací', TO_DATE('19.09.1899', 'dd.mm.yyyy'), NULL, NULL, 'informační technologie', 1, 'Bc.');

INSERT INTO uzemni_pusobnost(kralovstvi, zeme, region, hrabstvi, okres, obec)
VALUES(NULL, 'Česká republika', 'Čechy', NULL, 'Praha', 'Praha');
INSERT INTO uzemni_pusobnost(kralovstvi, zeme, region, hrabstvi, okres, obec)
VALUES(NULL, 'Česká republika', 'Morava', NULL, 'Brno-město', 'Brno');

INSERT INTO rozhodnuti(datum_rozhodnuti, datum_vykonatelnosti, text_vlastniho_rozhodnuti, text_oduvodneni)
VALUES(TO_DATE('01.03.2023', 'dd.mm.yyyy'), TO_DATE('01.09.2023', 'dd.mm.yyyy'), 'Patent na uvedený vynález se uděluje přihlašovateli.', 'Po důkladném průzkumu přihlášky a příslušného stavu techniky se vynález považuje za nový, nezřejmý a průmyslově využitelný. Proto se patent uděluje.');

INSERT INTO funkce(fk_funkce, nazev, zpusob_ziskani, delka_funkcniho_obdobi, datum_zavedeni, datum_zruseni)
VALUES(001, 'výkonný ředitel', 'výběrové řízení', 2190, TO_DATE('01.01.1993', 'dd.mm.yyyy'), NULL);

INSERT INTO zastava(fk_zastava_osobni_cislo, fk_kod, datum_zacatku, datum_konce, duvod_opusteni)
VALUES(3, 1, TO_DATE('01.01.2020', 'dd.mm.yyyy'), TO_DATE('01.01.2026', 'dd.mm.yyyy'), NULL);

INSERT INTO studuje(fk_studuje_osobni_cislo, fk_zkratka, datum_zacatku, datum_konce, uspesne_zakonceni)
VALUES(1, 1, TO_DATE('20.09.2020', 'dd.mm.yyyy'), NULL, NULL);

COMMIT;
